
name: Next.js CI/CD

on:  [push] 

jobs:
  build-and-deploy:
       runs-on:
       ubuntu-latest
           steps:
             -name: Checkout code
              uses: actions/checkout@v2
              -name: Install dependecies
              run: npm install
              -name: Build next js App
              run: npm run build
              -name: Start Next js App
              run: npm run start